###compare rsf dsv

#library(survcomp)
#library(dplyr)
library(compareC)

RS_composite_all.pred_score.dsv.train.txt = read.delim('../../RS_composite_all.pred_score.dsv.train.txt', header = F)
RS_composite_all.pred_score.dsv.test.txt = read.delim('../../RS_composite_all.pred_score.dsv.test.txt', header = F)
RS_composite_all.pred_score.rsf.train.txt = read.delim('../../rsf/RS_composite_all.pred_score.rsf.train.txt', header = F)
RS_composite_all.pred_score.rsf.test.txt = read.delim('../../rsf/RS_composite_all.pred_score.rsf.test.txt', header = F)
RS_composite_all.E_train.txt = read.delim('../../RS_composite_all.E_train.txt', header = F)
RS_composite_all.T_train.txt = read.delim('../../RS_composite_all.T_train.txt', header = F)
RS_composite_all.E_test.txt = read.delim('../../RS_composite_all.E_test.txt', header = F)
RS_composite_all.T_test.txt = read.delim('../../RS_composite_all.T_test.txt', header = F)

RS_composite_sans_base.pred_score.dsv.train.txt = read.delim('../../RS_composite_sans_base.pred_score.dsv.train.txt', header = F)
RS_composite_sans_base.pred_score.dsv.test.txt = read.delim('../../RS_composite_sans_base.pred_score.dsv.test.txt', header = F)
RS_composite_sans_base.pred_score.rsf.train.txt = read.delim('../../rsf/RS_composite_sans_base.pred_score.rsf.train.txt', header = F)
RS_composite_sans_base.pred_score.rsf.test.txt = read.delim('../../rsf/RS_composite_sans_base.pred_score.rsf.test.txt', header = F)
RS_composite_sans_base.E_train.txt = read.delim('../../RS_composite_sans_base.E_train.txt', header = F)
RS_composite_sans_base.T_train.txt = read.delim('../../RS_composite_sans_base.T_train.txt', header = F)
RS_composite_sans_base.E_test.txt = read.delim('../../RS_composite_sans_base.E_test.txt', header = F)
RS_composite_sans_base.T_test.txt = read.delim('../../RS_composite_sans_base.T_test.txt', header = F)

RS_composite_lab.pred_score.dsv.train.txt = read.delim('../../RS_composite_lab.pred_score.dsv.train.txt', header = F)
RS_composite_lab.pred_score.dsv.test.txt = read.delim('../../RS_composite_lab.pred_score.dsv.test.txt', header = F)
RS_composite_lab.pred_score.rsf.train.txt = read.delim('../../rsf/RS_composite_lab.pred_score.rsf.train.txt', header = F)
RS_composite_lab.pred_score.rsf.test.txt = read.delim('../../rsf/RS_composite_lab.pred_score.rsf.test.txt', header = F)
RS_composite_lab.E_train.txt = read.delim('../../RS_composite_lab.E_train.txt', header = F)
RS_composite_lab.T_train.txt = read.delim('../../RS_composite_lab.T_train.txt', header = F)
RS_composite_lab.E_test.txt = read.delim('../../RS_composite_lab.E_test.txt', header = F)
RS_composite_lab.T_test.txt = read.delim('../../RS_composite_lab.T_test.txt', header = F)

RS_composite_lab_demo.pred_score.dsv.train.txt = read.delim('../../RS_composite_lab_demo.pred_score.dsv.train.txt', header = F)
RS_composite_lab_demo.pred_score.dsv.test.txt = read.delim('../../RS_composite_lab_demo.pred_score.dsv.test.txt', header = F)
RS_composite_lab_demo.pred_score.rsf.train.txt = read.delim('../../rsf/RS_composite_lab_demo.pred_score.rsf.train.txt', header = F)
RS_composite_lab_demo.pred_score.rsf.test.txt = read.delim('../../rsf/RS_composite_lab_demo.pred_score.rsf.test.txt', header = F)
RS_composite_lab_demo.E_train.txt = read.delim('../../RS_composite_lab_demo.E_train.txt', header = F)
RS_composite_lab_demo.T_train.txt = read.delim('../../RS_composite_lab_demo.T_train.txt', header = F)
RS_composite_lab_demo.E_test.txt = read.delim('../../RS_composite_lab_demo.E_test.txt', header = F)
RS_composite_lab_demo.T_test.txt = read.delim('../../RS_composite_lab_demo.T_test.txt', header = F)

print('ALL')
print(compareC(RS_composite_all.T_train.txt[,1], RS_composite_all.E_train.txt[,1], RS_composite_all.pred_score.dsv.train.txt[,1], RS_composite_all.pred_score.rsf.train.txt[,1]))
print(compareC(RS_composite_all.T_test.txt[,1], RS_composite_all.E_test.txt[,1], RS_composite_all.pred_score.dsv.test.txt[,1], RS_composite_all.pred_score.rsf.test.txt[,1]))
print('SANS BASE')
print(compareC(RS_composite_sans_base.T_train.txt[,1], RS_composite_sans_base.E_train.txt[,1], RS_composite_sans_base.pred_score.dsv.train.txt[,1], RS_composite_sans_base.pred_score.rsf.train.txt[,1]))
print(compareC(RS_composite_sans_base.T_test.txt[,1], RS_composite_sans_base.E_test.txt[,1], RS_composite_sans_base.pred_score.dsv.test.txt[,1], RS_composite_sans_base.pred_score.rsf.test.txt[,1]))
print('lab')
print(compareC(RS_composite_lab.T_train.txt[,1], RS_composite_lab.E_train.txt[,1], RS_composite_lab.pred_score.dsv.train.txt[,1], RS_composite_lab.pred_score.rsf.train.txt[,1]))
print(compareC(RS_composite_lab.T_test.txt[,1], RS_composite_lab.E_test.txt[,1], RS_composite_lab.pred_score.dsv.test.txt[,1], RS_composite_lab.pred_score.rsf.test.txt[,1]))

print('lab demo')
print(compareC(RS_composite_lab_demo.T_train.txt[,1], RS_composite_lab_demo.E_train.txt[,1], RS_composite_lab_demo.pred_score.dsv.train.txt[,1], RS_composite_lab_demo.pred_score.rsf.train.txt[,1]))
print(compareC(RS_composite_lab_demo.T_test.txt[,1], RS_composite_lab_demo.E_test.txt[,1], RS_composite_lab_demo.pred_score.dsv.test.txt[,1], RS_composite_lab_demo.pred_score.rsf.test.txt[,1]))