#library(survcomp)
#library(dplyr)
library(compareC)

RS_composite_all.pred_score.dsv.train.txt = read.delim('../RS_composite_all.pred_score.dsv.train.txt', header = F)
RS_composite_all.pred_score.dsv.test.txt = read.delim('../RS_composite_all.pred_score.dsv.test.txt', header = F)
RS_composite_all.pred_score.cox.train.txt = read.delim('../RS_composite_all.pred_score.cox.train.txt', header = F)
RS_composite_all.pred_score.cox.test.txt = read.delim('../RS_composite_all.pred_score.cox.test.txt', header = F)
RS_composite_all.E_train.txt = read.delim('../RS_composite_all.E_train.txt', header = F)
RS_composite_all.T_train.txt = read.delim('../RS_composite_all.T_train.txt', header = F)
RS_composite_all.E_test.txt = read.delim('../RS_composite_all.E_test.txt', header = F)
RS_composite_all.T_test.txt = read.delim('../RS_composite_all.T_test.txt', header = F)

RS_composite_sans_base.pred_score.dsv.train.txt = read.delim('../RS_composite_sans_base.pred_score.dsv.train.txt', header = F)
RS_composite_sans_base.pred_score.dsv.test.txt = read.delim('../RS_composite_sans_base.pred_score.dsv.test.txt', header = F)
RS_composite_sans_base.pred_score.cox.train.txt = read.delim('../RS_composite_sans_base.pred_score.cox.train.txt', header = F)
RS_composite_sans_base.pred_score.cox.test.txt = read.delim('../RS_composite_sans_base.pred_score.cox.test.txt', header = F)
RS_composite_sans_base.E_train.txt = read.delim('../RS_composite_sans_base.E_train.txt', header = F)
RS_composite_sans_base.T_train.txt = read.delim('../RS_composite_sans_base.T_train.txt', header = F)
RS_composite_sans_base.E_test.txt = read.delim('../RS_composite_sans_base.E_test.txt', header = F)
RS_composite_sans_base.T_test.txt = read.delim('../RS_composite_sans_base.T_test.txt', header = F)

RS_composite_lab.pred_score.dsv.train.txt = read.delim('../RS_composite_lab.pred_score.dsv.train.txt', header = F)
RS_composite_lab.pred_score.dsv.test.txt = read.delim('../RS_composite_lab.pred_score.dsv.test.txt', header = F)
RS_composite_lab.pred_score.cox.train.txt = read.delim('../RS_composite_lab.pred_score.cox.train.txt', header = F)
RS_composite_lab.pred_score.cox.test.txt = read.delim('../RS_composite_lab.pred_score.cox.test.txt', header = F)
RS_composite_lab.E_train.txt = read.delim('../RS_composite_lab.E_train.txt', header = F)
RS_composite_lab.T_train.txt = read.delim('../RS_composite_lab.T_train.txt', header = F)
RS_composite_lab.E_test.txt = read.delim('../RS_composite_lab.E_test.txt', header = F)
RS_composite_lab.T_test.txt = read.delim('../RS_composite_lab.T_test.txt', header = F)

print('ALL')
compareC(RS_composite_all.T_train.txt[,1], RS_composite_all.E_train.txt[,1], RS_composite_all.pred_score.dsv.train.txt[,1], RS_composite_all.pred_score.cox.train.txt[,1])
compareC(RS_composite_all.T_test.txt[,1], RS_composite_all.E_test.txt[,1], RS_composite_all.pred_score.dsv.test.txt[,1], RS_composite_all.pred_score.cox.test.txt[,1])
print('SANS BASE')
compareC(RS_composite_sans_base.T_train.txt[,1], RS_composite_sans_base.E_train.txt[,1], RS_composite_sans_base.pred_score.dsv.train.txt[,1], RS_composite_sans_base.pred_score.cox.train.txt[,1])
compareC(RS_composite_sans_base.T_test.txt[,1], RS_composite_sans_base.E_test.txt[,1], RS_composite_sans_base.pred_score.dsv.test.txt[,1], RS_composite_sans_base.pred_score.cox.test.txt[,1])
print('lab')
compareC(RS_composite_lab.T_train.txt[,1], RS_composite_lab.E_train.txt[,1], RS_composite_lab.pred_score.dsv.train.txt[,1], RS_composite_lab.pred_score.cox.train.txt[,1])
compareC(RS_composite_lab.T_test.txt[,1], RS_composite_lab.E_test.txt[,1], RS_composite_lab.pred_score.dsv.test.txt[,1], RS_composite_lab.pred_score.cox.test.txt[,1])
